name: dds
num_steps: 50
stochasticity: 0.1
eps: 0.1
penalty: null
pct_chain_elapsed: 0
num_img_log: 10
log_freq: 10
batch_size: 8
beta_unit: False
add_corrector: False
guidance_strength: null
use_osem_nll: False