hydra: 
  run:
    dir: TEST_SINGLE/${dataset.part}_${dataset.poisson_scale}/${score_based_model.name}/${sampling.name}/${now:%Y-%m-%d-%H-%M-%S}/${hydra.job.override_dirname}
  sweep:
    dir: TEST/${dataset.part}_${dataset.poisson_scale}/${score_based_model.name}/${sampling.name}/${now:%Y-%m-%d-%H-%M-%S}/
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - dataset.name
          - dataset.part
          - dataset.poisson_scale
          - sampling.name
          - sampling
          - score_based_model.name
          - score_based_model

defaults:
  - _self_
  - dataset: brainweb2Ddataset
  - score_based_model: vpsde_image_scale
  - sampling: naive
seed: 42
num_images: 1
device: cuda